# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qstone.connectors.grpc.qpu_pb2 as qpu__pb2


class QPUStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunQuantumCircuit = channel.unary_unary(
            "/qstone.connectors.grpc.QPU/RunQuantumCircuit",
            request_serializer=qpu__pb2.Circuit.SerializeToString,
            response_deserializer=qpu__pb2.CircuitResponse.FromString,
        )


class QPUServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunQuantumCircuit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_QPUServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RunQuantumCircuit": grpc.unary_unary_rpc_method_handler(
            servicer.RunQuantumCircuit,
            request_deserializer=qpu__pb2.Circuit.FromString,
            response_serializer=qpu__pb2.CircuitResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "qstone.connectors.grpc.QPU", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class QPU(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunQuantumCircuit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/qstone.connectors.grpc.QPU/RunQuantumCircuit",
            qpu__pb2.Circuit.SerializeToString,
            qpu__pb2.CircuitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
